[package]
name = "fng_api_wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
serde = { version = "1.0.152", features = ["derive"] }
serde-aux = "4.1.2"
serde_json = "1.0.91"
thiserror = "1.0.38"
ureq = "2.6.2"